Repository HabitatMap/AircastingAndroid, pull requests merged in 2022-04, with the labels that each got.

#409 Chart left timestamp inaccurate; chart didn't update
  app/src/main/java/pl/llp/aircasting/database/data_classes/measurements.kt
  app/src/main/java/pl/llp/aircasting/database/repositories/ActiveSessionMeasurementsRepository.kt
  app/src/main/java/pl/llp/aircasting/database/repositories/MeasurementsRepository.kt
Labels: test

#411 Android New Map Renderer Update
  app/src/main/java/pl/llp/aircasting/screens/main/MainActivity.kt
Labels: enhancement

#410 Navigation Issues Fix
  app/src/main/java/pl/llp/aircasting/models/Session.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/DashboardFragment.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/SessionsViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/following/FollowingController.kt
  app/src/main/java/pl/llp/aircasting/screens/lets_start/LetsStartViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/screens/main/MainViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/NewSessionActivity.kt
  app/src/main/java/pl/llp/aircasting/screens/session_view/graph/GraphActivity.kt
  app/src/main/java/pl/llp/aircasting/screens/session_view/map/MapActivity.kt
  app/src/main/java/pl/llp/aircasting/screens/settings/clear_sd_card/ClearSDCardActivity.kt
  app/src/main/java/pl/llp/aircasting/screens/settings/my_account/MyAccountActivity.kt
  app/src/main/java/pl/llp/aircasting/screens/sync/SyncActivity.kt
  app/src/main/res/layout/empty_mobile_dashboard.xml
  app/src/main/res/layout/fragment_sessions_tab.xml
Labels: bug

#407 Sd sync issue
  app/src/main/java/pl/llp/aircasting/database/data_classes/measurements.kt
  app/src/main/java/pl/llp/aircasting/database/repositories/MeasurementsRepository.kt
  app/src/main/java/pl/llp/aircasting/di/SensorsModule.kt
  app/src/main/java/pl/llp/aircasting/sensor/airbeam3/sync/SDCardFixedSessionsProcessor.kt
  app/src/main/java/pl/llp/aircasting/sensor/airbeam3/sync/SDCardMobileSessionsProcessor.kt
  app/src/main/java/pl/llp/aircasting/sensor/airbeam3/sync/SDCardSessionsProcessor.kt
  app/src/main/java/pl/llp/aircasting/sensor/airbeam3/sync/SDCardSyncService.kt
Labels: test

#412 Chart first dot disappearing on refresh
  app/src/main/java/pl/llp/aircasting/screens/dashboard/charts/ChartData.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/charts/ChartRefreshService.kt
Labels: test

#414 Airbeam Reconnect Issue | Plan B
  app/src/main/AndroidManifest.xml
  app/src/main/java/pl/llp/aircasting/exceptions/ErrorHandler.kt
  app/src/main/java/pl/llp/aircasting/lib/APIHelper.kt
  app/src/main/java/pl/llp/aircasting/lib/extensions.kt
  app/src/main/java/pl/llp/aircasting/networking/services/DownloadMeasurementsCallback.kt
  app/src/main/java/pl/llp/aircasting/screens/common/BaseDialog.kt
  app/src/main/java/pl/llp/aircasting/screens/common/BatteryAlertDialog.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/active/MobileActiveController.kt
  app/src/main/java/pl/llp/aircasting/screens/lets_start/LetsStartController.kt
  app/src/main/java/pl/llp/aircasting/screens/main/MainActivity.kt
  app/src/main/java/pl/llp/aircasting/screens/main/MainController.kt
  app/src/main/java/pl/llp/aircasting/screens/main/MainViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/NewSessionController.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/session_details/FixedSessionDetailsController.kt
  app/src/main/java/pl/llp/aircasting/screens/session_view/graph/GraphContainer.kt
  app/src/main/java/pl/llp/aircasting/sensor/AirBeamReconnector.kt
  app/src/main/java/pl/llp/aircasting/sensor/SensorService.kt
  app/src/main/res/layout/battery_dialog_alert_aircasting.xml
  app/src/main/res/values-b+es/strings.xml
  app/src/main/res/values-fr-rFR/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug, test

#423 Chart left timestamp inaccurate
  app/src/main/java/pl/llp/aircasting/database/repositories/ActiveSessionMeasurementsRepository.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/SessionViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/SessionsController.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/charts/ChartAveragesCreator.kt
Labels: test

#426 Fatal Exception: android.database.sqlite.SQLiteException
  app/schemas/io.lunarlogic.aircasting.database.AppDatabase/17.json
  app/schemas/io.lunarlogic.aircasting.database.AppDatabase/18.json
  app/schemas/io.lunarlogic.aircasting.database.AppDatabase/19.json
  app/schemas/io.lunarlogic.aircasting.database.AppDatabase/20.json
  app/schemas/io.lunarlogic.aircasting.database.AppDatabase/21.json
  app/schemas/io.lunarlogic.aircasting.database.AppDatabase/22.json
  app/schemas/io.lunarlogic.aircasting.database.AppDatabase/23.json
  app/schemas/io.lunarlogic.aircasting.database.AppDatabase/24.json
  app/schemas/io.lunarlogic.aircasting.database.AppDatabase/25.json
  app/schemas/io.lunarlogic.aircasting.database.AppDatabase/26.json
  app/schemas/io.lunarlogic.aircasting.database.AppDatabase/27.json
  app/schemas/pl.llp.aircasting.database.AppDatabase/27.json
  app/schemas/pl.llp.aircasting.database.AppDatabase/28.json
  app/schemas/pl.llp.aircasting.database.AppDatabase/29.json
  app/src/main/java/pl/llp/aircasting/database/DatabaseProvider.kt
  app/src/main/java/pl/llp/aircasting/database/data_classes/measurements.kt
  app/src/main/java/pl/llp/aircasting/database/data_classes/sessions.kt
  app/src/main/java/pl/llp/aircasting/database/migrations/migration_29.kt
Labels: bug

#427 Destructive migration db version 30
  app/build.gradle
  app/src/main/java/pl/llp/aircasting/database/DatabaseProvider.kt
Labels: wip

#433 Bluetooth manager crash android 12
  app/src/main/AndroidManifest.xml
  app/src/main/java/pl/llp/aircasting/bluetooth/BluetoothManager.kt
  app/src/main/java/pl/llp/aircasting/bluetooth/BluetoothManagerDefault.kt
  app/src/main/java/pl/llp/aircasting/bluetooth/BluetoothRuntimePermissionManager.kt
  app/src/main/java/pl/llp/aircasting/di/PermissionsModule.kt
  app/src/main/java/pl/llp/aircasting/permissions/PermissionsManager.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/NewSessionController.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/connect_airbeam/TurnOnBluetoothViewMvc.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/connect_airbeam/TurnOnBluetoothViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/screens/settings/clear_sd_card/ClearSDCardController.kt
  app/src/main/java/pl/llp/aircasting/screens/sync/SyncController.kt
Labels: test
