Repository HabitatMap/AircastingAndroid, pull requests merged in 2022-03, with the labels that each got.

#365 Updates + Refactoring
  .idea/gradle.xml
  app/build.gradle
  app/src/androidTest/java/pl/llp/aircasting/MobileSessionTest.kt
  app/src/androidTest/java/pl/llp/aircasting/MyAccountTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/pl/llp/aircasting/AppComponent.kt
  app/src/main/java/pl/llp/aircasting/bluetooth/BluetoothManager.kt
  app/src/main/java/pl/llp/aircasting/lib/Settings.kt
  app/src/main/java/pl/llp/aircasting/permissions/PermissionsManager.kt
  app/src/main/java/pl/llp/aircasting/screens/create_account/CreateAccountController.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/DashboardFragment.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/SessionsRecyclerAdapter.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/active/MobileActiveController.kt
  app/src/main/java/pl/llp/aircasting/screens/login/ForgotPasswordDialog.kt
  app/src/main/java/pl/llp/aircasting/screens/login/LoginActivity.kt
  app/src/main/java/pl/llp/aircasting/screens/login/LoginController.kt
  app/src/main/java/pl/llp/aircasting/screens/login/LoginViewMvc.kt
  app/src/main/java/pl/llp/aircasting/screens/login/LoginViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/screens/main/MainActivity.kt
  app/src/main/java/pl/llp/aircasting/screens/main/MainController.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/NewSessionActivity.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/NewSessionController.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/choose_location/ChooseLocationViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/screens/session_view/measurement_table_container/MeasurementsTableContainer.kt
  app/src/main/java/pl/llp/aircasting/screens/settings/my_account/MyAccountController.kt
  app/src/main/java/pl/llp/aircasting/screens/sync/SyncActivity.kt
  app/src/main/java/pl/llp/aircasting/sensor/SensorService.kt
  app/src/main/java/pl/llp/aircasting/services/AveragedMeasurementsService.kt
  app/src/main/java/pl/llp/aircasting/services/AveragingBackgroundService.kt
  app/src/main/java/pl/llp/aircasting/services/AveragingService.kt
  app/src/main/res/layout/activity_create_account.xml
  app/src/main/res/layout/activity_graph.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_sync.xml
  app/src/main/res/layout/add_note_bottom_sheet.xml
  app/src/main/res/layout/disconnected_view.xml
  app/src/main/res/layout/edit_note_bottom_sheet.xml
  app/src/main/res/layout/edit_session_bottom_sheet.xml
  app/src/main/res/layout/fragment_choose_location.xml
  app/src/main/res/layout/fragment_fixed_session_confirmation.xml
  app/src/main/res/layout/fragment_fixed_session_details.xml
  app/src/main/res/layout/fragment_mobile_session_confirmation.xml
  app/src/main/res/layout/fragment_select_device_type.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/hlu_dialog.xml
  app/src/main/res/layout/hlu_slider.xml
  app/src/main/res/layout/learn_more_onboarding_measure_and_map.xml
  app/src/main/res/layout/learn_more_onboarding_your_privacy.xml
  app/src/main/res/layout/measurement_value.xml
  app/src/main/res/layout/more_info_bottom_sheet.xml
  app/src/main/res/layout/onboarding_get_started.xml
  app/src/main/res/layout/prominent_app_bar.xml
  app/src/main/res/layout/select_device_group_header.xml
  app/src/main/res/layout/session_card.xml
  app/src/main/res/layout/session_details_statistics_view.xml
Labels: Updates

#366 Map Locate fix with zero values
  app/build.gradle
  app/src/main/java/pl/llp/aircasting/location/LocationHelper.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/ShareSessionBottomSheet.kt
  app/src/main/java/pl/llp/aircasting/screens/session_view/StatisticsContainer.kt
  app/src/main/java/pl/llp/aircasting/screens/session_view/map/MapContainer.kt
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: bug

#373 French Support
  app/src/main/res/values-b+es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#376 Added support for French - Fix
  app/build.gradle
  app/src/main/java/pl/llp/aircasting/models/Session.kt
  app/src/main/res/values-fr-rFR/strings.xml
Labels: enhancement

#378 Chart averages not displayed & Update problems fix
  app/src/main/java/pl/llp/aircasting/database/repositories/SessionsRepository.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/SessionViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/SessionsController.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/active/MobileActiveController.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/active/MobileActiveSessionViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/charts/Chart.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/NewSessionActivity.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/NewSessionViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/sensor/SensorService.kt
Labels: bug

#379 Graph Vertical Space Fix
  app/src/main/res/layout/graph.xml
Labels: bug

#360 Settings: celsius
  app/src/main/java/pl/llp/aircasting/lib/Settings.kt
  app/src/main/java/pl/llp/aircasting/lib/TemperatureConverter.kt
  app/src/main/java/pl/llp/aircasting/models/Measurement.kt
  app/src/main/java/pl/llp/aircasting/models/MeasurementStream.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/SessionViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/charts/Chart.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/charts/ChartData.kt
  app/src/main/java/pl/llp/aircasting/screens/main/MainActivity.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/NewSessionActivity.kt
  app/src/main/java/pl/llp/aircasting/screens/session_view/SessionDetailsViewController.kt
  app/src/main/java/pl/llp/aircasting/screens/session_view/SessionDetailsViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/screens/session_view/StatisticsContainer.kt
  app/src/main/java/pl/llp/aircasting/screens/session_view/graph/GraphContainer.kt
  app/src/main/java/pl/llp/aircasting/screens/session_view/graph/TargetZoneCombinedChart.kt
  app/src/main/java/pl/llp/aircasting/screens/session_view/hlu/HLUDialog.kt
  app/src/main/java/pl/llp/aircasting/screens/session_view/hlu/HLUSlider.kt
  app/src/main/java/pl/llp/aircasting/screens/session_view/measurement_table_container/MeasurementsTableContainer.kt
  app/src/main/java/pl/llp/aircasting/screens/settings/SettingsController.kt
  app/src/main/java/pl/llp/aircasting/screens/settings/SettingsViewMvc.kt
  app/src/main/java/pl/llp/aircasting/screens/settings/SettingsViewMvcImpl.kt
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/hlu_dialog.xml
  app/src/main/res/layout/hlu_slider.xml
  app/src/main/res/layout/measurement_header.xml
Labels: enhancement

#374 Maps SDK Update
  app/build.gradle
  app/src/main/java/pl/llp/aircasting/lib/BitmapHelper.kt
  app/src/main/java/pl/llp/aircasting/lib/SessionBoundingBox.kt
  app/src/main/java/pl/llp/aircasting/lib/extensions.kt
  app/src/main/java/pl/llp/aircasting/networking/services/ApiService.kt
  app/src/main/java/pl/llp/aircasting/networking/services/DownloadMeasurementsCallback.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/SessionsController.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/active/MobileActiveController.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/NewSessionController.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/choose_location/ChooseLocationViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/confirmation/ConfirmationController.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/confirmation/ConfirmationViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/confirmation/FixedSessionConfirmationViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/screens/session_view/SessionDetailsViewController.kt
  app/src/main/java/pl/llp/aircasting/screens/session_view/map/AircastingHeatmap.kt
  app/src/main/java/pl/llp/aircasting/screens/session_view/map/MapContainer.kt
  app/src/main/java/pl/llp/aircasting/screens/sync/SyncController.kt
  app/src/main/java/pl/llp/aircasting/screens/sync/syncing/AirbeamSyncingController.kt
  app/src/main/java/pl/llp/aircasting/sensor/AirBeamReconnector.kt
  app/src/main/java/pl/llp/aircasting/sensor/SessionManager.kt
  app/src/main/java/pl/llp/aircasting/sensor/airbeam3/sync/SDCardClearService.kt
  app/src/main/java/pl/llp/aircasting/sensor/airbeam3/sync/SDCardDownloadService.kt
  app/src/main/java/pl/llp/aircasting/sensor/airbeam3/sync/SDCardSyncService.kt
  app/src/main/java/pl/llp/aircasting/sensor/microphone/MicrophoneReader.kt
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/activity_new_session.xml
  app/src/main/res/layout/fragment_choose_location.xml
  app/src/main/res/layout/fragment_fixed_session_confirmation.xml
  app/src/main/res/layout/fragment_mobile_session_confirmation.xml
Labels: Updates

#380 Fix for missing parts on Master branch
  app/src/main/java/pl/llp/aircasting/lib/extensions.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/NewSessionActivity.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/confirmation/ConfirmationViewMvcImpl.kt
Labels: bug

#383 Reoccurring toast
  app/src/main/java/pl/llp/aircasting/models/observers/AppLifecycleObserver.kt
  app/src/main/java/pl/llp/aircasting/networking/services/SessionsSyncService.kt
Labels: bug

#385 BLUETOOTH permissions
  app/src/main/java/pl/llp/aircasting/lib/ResultCodes.kt
  app/src/main/java/pl/llp/aircasting/permissions/PermissionsManager.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/NewSessionController.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/NewSessionWizardNavigator.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/select_device_type/SelectDeviceTypeController.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/select_device_type/SelectDeviceTypeFragment.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/select_device_type/SelectDeviceTypeViewMvc.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/select_device_type/SelectDeviceTypeViewMvcImpl.kt
  app/src/main/res/values-b+es/strings.xml
  app/src/main/res/values-fr-rFR/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement, Updates

#387 Location Toast Issue
  app/src/main/AndroidManifest.xml
  app/src/main/java/pl/llp/aircasting/screens/new_session/NewSessionController.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/connect_airbeam/TurnOnAirBeamViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/connect_airbeam/TurnOnBluetoothViewMvcImpl.kt
  app/src/main/res/layout/fragment_turn_on_bluetooth.xml
  app/src/main/res/values-b+es/strings.xml
  app/src/main/res/values-fr-rFR/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug

#390 Improve aesthetics
  app/src/main/res/layout/onboarding_get_started.xml
  app/src/main/res/values/colors.xml
Labels: bug

#394 Dark theme Support + feature in Settings
  app/src/main/java/pl/llp/aircasting/AircastingApplication.kt
  app/src/main/java/pl/llp/aircasting/lib/Settings.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/SessionsViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/screens/settings/SettingsController.kt
  app/src/main/java/pl/llp/aircasting/screens/settings/SettingsViewMvc.kt
  app/src/main/java/pl/llp/aircasting/screens/settings/SettingsViewMvcImpl.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_myaccount.xml
  app/src/main/res/layout/fragment_choose_location.xml
  app/src/main/res/layout/fragment_fixed_session_confirmation.xml
  app/src/main/res/layout/fragment_fixed_session_details.xml
  app/src/main/res/layout/fragment_lets_start.xml
  app/src/main/res/layout/fragment_mobile_session_confirmation.xml
  app/src/main/res/layout/fragment_mobile_session_details.xml
  app/src/main/res/layout/fragment_select_device.xml
  app/src/main/res/layout/fragment_select_device_type.xml
  app/src/main/res/layout/fragment_sessions_tab.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_turn_off_location_services.xml
  app/src/main/res/layout/fragment_turn_on_bluetooth.xml
  app/src/main/res/layout/fragment_turn_on_location_services.xml
  app/src/main/res/layout/prominent_app_bar.xml
  app/src/main/res/values-b+es/strings.xml
  app/src/main/res/values-fr-rFR/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#395 Reorder icon appearance with at least two followed sessions
  app/src/main/java/pl/llp/aircasting/lib/AppBar.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/following/FollowingSessionViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/reordering_dashboard/ReorderingDashboardViewMvcImpl.kt
  app/src/main/res/layout/prominent_app_bar.xml
Labels: bug

#399 Chart averages; Chart times fix
  app/src/main/java/pl/llp/aircasting/networking/services/DownloadMeasurementsCallback.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/SessionsRecyclerAdapter.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/charts/ChartData.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/charts/ChartRefreshService.kt
Labels: bug

#401 Dependencies | Updates
  app/build.gradle
Labels: Updates

#405 java.lang.NullPointerException
  app/src/main/java/pl/llp/aircasting/networking/params/SessionParams.kt
Labels: bug

#406 Resource ID #0x7f070016 type #0x3 is not valid | Fix
  app/src/main/java/pl/llp/aircasting/screens/dashboard/DeleteSessionBottomSheet.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/ShareSessionBottomSheet.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/active/MobileActiveSessionViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/screens/session_view/graph/GraphDataGenerator.kt
  app/src/main/java/pl/llp/aircasting/screens/sync/refreshed/RefreshedSessionsViewMvcImpl.kt
Labels: bug

#397 AppBar Memory Leak Fix
  app/src/main/java/pl/llp/aircasting/lib/AppBar.kt
  app/src/main/java/pl/llp/aircasting/lib/ValidationHelper.kt
  app/src/main/java/pl/llp/aircasting/lib/extensions.kt
  app/src/main/java/pl/llp/aircasting/screens/common/BaseController.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/DashboardFragment.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/DashboardViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/SessionsController.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/ShareSessionBottomSheet.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/dormant/MobileDormantController.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/fixed/FixedController.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/following/FollowingController.kt
  app/src/main/java/pl/llp/aircasting/screens/dashboard/reordering_dashboard/ReorderingDashboardViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/screens/lets_start/LetsStartController.kt
  app/src/main/java/pl/llp/aircasting/screens/lets_start/LetsStartFragment.kt
  app/src/main/java/pl/llp/aircasting/screens/main/MainActivity.kt
  app/src/main/java/pl/llp/aircasting/screens/main/MainViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/NewSessionActivity.kt
  app/src/main/java/pl/llp/aircasting/screens/new_session/NewSessionController.kt
  app/src/main/java/pl/llp/aircasting/screens/session_view/SessionDetailsViewController.kt
  app/src/main/java/pl/llp/aircasting/screens/session_view/graph/GraphActivity.kt
  app/src/main/java/pl/llp/aircasting/screens/session_view/graph/GraphController.kt
  app/src/main/java/pl/llp/aircasting/screens/session_view/map/MapActivity.kt
  app/src/main/java/pl/llp/aircasting/screens/session_view/map/MapController.kt
  app/src/main/java/pl/llp/aircasting/screens/settings/SettingsFragment.kt
  app/src/main/java/pl/llp/aircasting/screens/settings/clear_sd_card/ClearSDCardActivity.kt
  app/src/main/java/pl/llp/aircasting/screens/settings/my_account/MyAccountActivity.kt
  app/src/main/java/pl/llp/aircasting/screens/sync/SyncActivity.kt
  app/src/main/res/layout/prominent_app_bar.xml
Labels: bug

#408 Fixed Session | Wrong Navigation
  app/src/main/java/pl/llp/aircasting/screens/new_session/NewSessionActivity.kt
Labels: bug
