Repository HabitatMap/AircastingAndroid, pull requests merged in 2022-05, with the labels that each got.

#431 Endpoints | APIService
  app/src/main/java/pl/llp/aircasting/networking/Constants.kt
  app/src/main/java/pl/llp/aircasting/networking/services/ApiService.kt
Labels: enhancement, Refactoring

#440 Search and follow bottomsheet statistics container
  app/src/main/java/pl/llp/aircasting/ui/view/screens/search/SearchFixedBottomSheet.kt
  app/src/main/java/pl/llp/aircasting/util/BindingAdapter.kt
  app/src/main/res/layout/measurements_table_binding.xml
  app/src/main/res/layout/search_follow_bottom_sheet.xml
  app/src/main/res/layout/stream_measurement_header_and_value.xml
Labels: wip

#445 Ext Session Table | Follow Session
  app/src/main/java/pl/llp/aircasting/data/local/DatabaseProvider.kt
  app/src/main/java/pl/llp/aircasting/data/local/dao/ExtSessionDao.kt
  app/src/main/java/pl/llp/aircasting/data/local/entity/ExtSessionDBObject.kt
Labels: enhancement, Search Feature

#448 Converting the Groovy to Kotlin DSL
  app/build.gradle
  app/build.gradle.kts
  app/proguard-rules.pro
  build.gradle
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/AppConfig.kt
  buildSrc/src/main/java/AppDependencies.kt
  buildSrc/src/main/java/Versions.kt
  settings.gradle
  settings.gradle.kts
Labels: enhancement, Refactoring
