Repository HabitatMap/AircastingAndroid, pull requests merged in 2022-09, with the labels that each got.

#646 Following > graph: time on right side of graph doesn't update
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/charts/Chart.kt
Labels: bug, Refactoring

#650 Only the original thread that created
  app/src/main/java/pl/llp/aircasting/ui/view/fragments/DashboardFragment.kt
  app/src/main/java/pl/llp/aircasting/ui/view/fragments/ReorderingDashboardFragment.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/DashboardViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/main/MainController.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/session_view/graph/GraphActivity.kt
Labels: bug, Refactoring

#651 When finishing the session on MobileActive tab | AirBeam 3
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/active/MobileActiveController.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/sync/SyncActivity.kt
  app/src/main/java/pl/llp/aircasting/util/Settings.kt
Labels: bug, Refactoring

#652 Settings screen empty after finishing mobile session
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/active/FinishSessionConfirmationDialog.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/session_view/graph/GraphViewMobileActiveMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/session_view/graph/GraphViewMvcImplFactory.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/session_view/map/MapController.kt
Labels: bug, Refactoring

#654 Revert autofill
  app/src/main/java/pl/llp/aircasting/ui/view/common/BottomSheet.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/new_session/session_details/FixedSessionDetailsController.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/new_session/session_details/FixedSessionDetailsViewMvc.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/new_session/session_details/FixedSessionDetailsViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/new_session/session_details/NetworkPasswordDialog.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/new_session/session_details/SessionDetailsController.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/new_session/session_details/SessionDetailsFragment.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/new_session/session_details/WeDoNotLeakPasswordsBottomSheet.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/onboarding/your_privacy/LearnMoreYourPrivacyBottomSheet.kt
  app/src/main/res/layout/learn_more_onboarding_your_privacy.xml
  app/src/main/res/layout/network_password_dialog.xml
  app/src/main/res/layout/we_do_not_leak_passwords_bottom_sheet.xml
  app/src/main/res/values-b+es/strings.xml
  app/src/main/res/values-fr-rFR/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: invalid

#656 Go to login screen from background if logout is in progress
  app/src/main/java/pl/llp/aircasting/ui/view/screens/main/MainController.kt
Labels: bug

#657 Self expanding mobile active cards
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionPresenter.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/active/MobileActiveSessionViewMvcImpl.kt
Labels: bug

#660 Revert local changes added by accident
  app/src/main/java/pl/llp/aircasting/util/helpers/location/LocationHelper.kt
  app/src/main/java/pl/llp/aircasting/util/helpers/services/AveragingService.kt
Labels: invalid

#669 Let's start | Layout
  app/src/main/res/layout/fragment_lets_begin.xml
Labels: Refactoring

#671 Update Graph end time
  app/src/main/java/pl/llp/aircasting/ui/view/screens/session_view/graph/GraphContainer.kt
Labels: bug

#676 Changes after code review
  app/src/main/res/layout/edit_note_bottom_sheet.xml
  app/src/main/res/values-b+es/strings.xml
  app/src/main/res/values-fr-rFR/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: Refactoring

#681 New validations PR
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/active/AddNoteBottomSheet.kt
  app/src/main/res/layout/add_note_bottom_sheet.xml
Labels: bug, Refactoring

#685 Revert "Fix for BottomSheet style"
  app/src/main/res/layout/search_follow_bottom_sheet.xml
  app/src/main/res/values/styles.xml
Labels: invalid

#684 Show image note after logout
  app/src/androidTest/java/pl/llp/aircasting/di/TestApiModule.kt
  app/src/androidTest/java/pl/llp/aircasting/di/mocks/FakeApiServiceFactory.kt
  app/src/androidTest/java/pl/llp/aircasting/di/mocks/FakeSettings.kt
  app/src/main/java/pl/llp/aircasting/data/api/services/ApiServiceFactory.kt
  app/src/main/java/pl/llp/aircasting/data/api/util/ApiConstants.kt
  app/src/main/java/pl/llp/aircasting/di/modules/ApiModule.kt
  app/src/main/java/pl/llp/aircasting/di/modules/NetworkModule.kt
  app/src/main/java/pl/llp/aircasting/util/NoteResponseParser.kt
  app/src/main/java/pl/llp/aircasting/util/Settings.kt
Labels: bug

#686 Attach a note | Refactor
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/active/AddNoteBottomSheet.kt
Labels: Refactoring

#691 Replace "photo" field with "photo_location" field in NoteResponse
  app/src/main/java/pl/llp/aircasting/data/api/response/NoteResponse.kt
  app/src/main/java/pl/llp/aircasting/util/NoteResponseParser.kt
Labels: Refactoring
