Repository HabitatMap/AircastingAndroid, pull requests merged in 2022-07, with the labels that each got.

#501 Excluding commons-logging and httpclient; they interfered with other …
  app/build.gradle.kts
Labels: chore

#500 Settings | Profile Name
  app/src/main/java/pl/llp/aircasting/ui/view/screens/settings/SettingsController.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/settings/SettingsViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/settings/my_account/MyAccountViewMvcImpl.kt
  app/src/main/res/layout/activity_myaccount.xml
  app/src/main/res/layout/fragment_settings.xml
Labels: enhancement, Updates

#502 Improvements | Adapter
  app/src/main/java/pl/llp/aircasting/ui/view/fragments/ReorderingDashboardFragment.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/reordering_dashboard/ReorderingDashboardPagerAdapter.kt
  buildSrc/src/main/java/Versions.kt
Labels: Refactoring

#504 Shrink map markers
  app/src/main/res/drawable/map_dot_selected.xml
  app/src/main/res/drawable/map_dot_with_circle_inside.xml
Labels: Refactoring, Search Feature

#503 Reduce APK size | ProGuard
  app/build.gradle.kts
  app/proguard-rules.pro
  buildSrc/src/main/java/AppDependencies.kt
Labels: enhancement, Updates, Refactoring

#505 Mic sessions left timestamp fix
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/charts/SessionChartDataCalculator.kt
Labels: bug

#514 Map: Session marker doesn't shrink
  app/src/main/java/pl/llp/aircasting/ui/view/adapters/FixedFollowAdapter.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/search/SearchFixedResultActivity.kt
  app/src/main/java/pl/llp/aircasting/util/extensions.kt
Labels: bug, Search Feature

#515 Session Card and Dot Issue
  app/src/main/java/pl/llp/aircasting/ui/view/adapters/FixedFollowAdapter.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/search/SearchFixedResultActivity.kt
Labels: bug, Refactoring, Search Feature

#516 Satellite + Layout update
  app/src/main/java/pl/llp/aircasting/ui/view/screens/search/SearchFixedResultActivity.kt
  app/src/main/res/layout/activity_search_follow_result.xml
Labels: Refactoring, Search Feature

#517 S&F > map: "Results for:" is incorrect
  app/src/main/java/pl/llp/aircasting/ui/view/screens/search/SearchFixedSessionsActivity.kt
Labels: bug, Search Feature

#520 Vertical Space | Redu button
  app/src/main/res/layout/activity_search_follow_result.xml
Labels: bug, Search Feature

#519 Satellite View Should show details
  app/src/main/java/pl/llp/aircasting/util/extensions.kt
Labels: bug, Refactoring

#518 Running on background Dialog
  app/src/main/java/pl/llp/aircasting/ui/view/fragments/DashboardFragment.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/main/MainActivity.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/main/MainController.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/new_session/NewSessionActivity.kt
  app/src/main/res/values/strings.xml
Labels: bug, Refactoring

#521 Glued ab2 and ab3 responses in repository
  app/src/main/java/pl/llp/aircasting/data/api/repository/ActiveFixedSessionsInRegionRepository.kt
  app/src/main/java/pl/llp/aircasting/data/api/util/StringConstants.kt
Labels: bug

#525 S&F: search returns wrong sessions
  app/src/main/java/pl/llp/aircasting/ui/view/screens/search/SearchFixedSessionsActivity.kt
Labels: Refactoring, Search Feature

#523 Set Pm2.5 as default
  app/src/main/java/pl/llp/aircasting/data/api/util/StringConstants.kt
  app/src/main/java/pl/llp/aircasting/data/model/MeasurementStream.kt
  app/src/main/java/pl/llp/aircasting/data/model/SensorName.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionPresenter.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/search/SearchFixedBottomSheet.kt
Labels: bug, Refactoring, Search Feature

#526 S&F > bottomsheet: map, chart, buttons not displayed properly
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/EditSessionBottomSheet.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/active/DisconnectedView.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/active/EditNoteBottomSheet.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/main/MainViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/new_session/connect_airbeam/ConnectingAirBeamViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/new_session/select_device/SelectDeviceViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/search/SearchFixedBottomSheet.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/search/SearchFixedResultActivity.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/session_view/SessionDetailsViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/settings/clear_sd_card/clearing_sd_card/ClearingSDCardViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/sync/refreshing/RefreshingSessionsViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/sync/syncing/AirbeamSyncingViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/util/AnimatedLoader.kt
  app/src/main/java/pl/llp/aircasting/util/SensorThresholdColorPicker.kt
  app/src/main/java/pl/llp/aircasting/util/extensions.kt
  app/src/main/res/layout/activity_search_follow_result.xml
  app/src/main/res/layout/search_follow_bottom_sheet.xml
Labels: bug, Search Feature

#510 Save card UI state
  app/src/main/java/pl/llp/aircasting/AircastingApplication.kt
  app/src/main/java/pl/llp/aircasting/data/local/repository/ExpandedCardsRepository.kt
  app/src/main/java/pl/llp/aircasting/di/modules/SettingsModule.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionCardListener.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionsController.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionsRecyclerAdapter.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionsViewMvc.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionsViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/active/FinishSessionListener.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/following/FollowingController.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/settings/my_account/MyAccountController.kt
  app/src/main/java/pl/llp/aircasting/util/Settings.kt
  app/src/main/java/pl/llp/aircasting/util/extensions.kt
Labels: enhancement

#529 S&F: search returns wrong sessions
  app/src/main/java/pl/llp/aircasting/ui/view/screens/search/SearchFixedSessionsActivity.kt
Labels: bug, Search Feature

#530 S&F > Bottomsheet: map, chart, buttons not displayed properly
  app/src/main/java/pl/llp/aircasting/util/extensions.kt
  app/src/main/res/layout/search_follow_bottom_sheet.xml
Labels: bug, Refactoring, Search Feature

#534 Midnight line is Missing | Ext sessions
  app/src/main/java/pl/llp/aircasting/ui/view/screens/session_view/graph/GraphDataGenerator.kt
  app/src/main/res/layout/graph.xml
  app/src/main/res/values-b+es/strings.xml
  app/src/main/res/values-fr-rFR/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug, Refactoring, Search Feature

#535 Align session name to the right on reconnect screen | Session Card
  app/src/main/res/layout/session_card.xml
Labels: bug, Refactoring

#537 Made all the cards collapsed on in reorder adapter
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/reordering_following/ReorderingFollowingRecyclerAdapter.kt
Labels: bug

#539 Leaked GCP API keys
  .gitignore
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/pl/llp/aircasting/util/extensions.kt
  build.gradle.kts
  buildSrc/src/main/java/Versions.kt
Labels: enhancement, wip, Refactoring

#541 Removed recursion
  app/src/main/java/pl/llp/aircasting/ui/view/fragments/DashboardFragment.kt
Labels: bug

#538 Fixed Session Overlap | Measurements Table
  app/src/main/java/pl/llp/aircasting/data/model/Session.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/following/FollowingSessionViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/session_view/measurement_table_container/MeasurementsTableContainer.kt
Labels: bug, wip, Refactoring

#547 Refactor | Session Presenter
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionPresenter.kt
Labels: Refactoring

#546 Refactoring | BaseActivity
  app/src/main/java/pl/llp/aircasting/ui/view/screens/search/SearchFixedResultActivity.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/search/SearchFixedSessionsActivity.kt
Labels: Refactoring, Search Feature

#550 Fatal Exception: java.util.NoSuchElementException
  app/src/main/java/pl/llp/aircasting/data/model/MeasurementStream.kt
Labels: bug, test, Refactoring

#566 Made notes appear on graph
  app/src/main/java/pl/llp/aircasting/data/model/Note.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/session_view/graph/GraphDataGenerator.kt
Labels: bug

#572 Zoom level limit
  app/src/main/java/pl/llp/aircasting/ui/view/screens/search/SearchFixedResultActivity.kt
Labels: bug, test, Refactoring, Search Feature

#571 Graph Container | Crash
  app/src/main/java/pl/llp/aircasting/ui/view/screens/session_view/graph/GraphContainer.kt
Labels: bug, test, Refactoring
