Repository HabitatMap/AircastingAndroid, pull requests merged in 2022-08, with the labels that each got.

#578 Swapped java annotations with kotlin
  app/src/main/java/pl/llp/aircasting/di/modules/ViewModelModule.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/search/SearchFixedSessionActivity.kt
  app/src/main/java/pl/llp/aircasting/ui/viewmodel/ViewModelFactory.kt
Labels: Refactoring

#582 CircleCi Roles refactor
  .circleci/config.yml
  app/build.gradle.kts
Labels: Refactoring, chore

#577 No sessions displayed west of specific longitude
  app/src/main/java/pl/llp/aircasting/data/api/repository/ActiveFixedSessionsInRegionRepository.kt
  app/src/main/java/pl/llp/aircasting/util/CalendarUtils.kt
Labels: bug, wip, test, Refactoring, Search Feature

#587 S&F | Sessions-refactor
  app/src/main/java/pl/llp/aircasting/data/api/repository/ActiveFixedSessionsInRegionRepository.kt
  app/src/main/java/pl/llp/aircasting/util/CalendarUtils.kt
Labels: bug, Refactoring, Search Feature

#588 Make DidYouKnow box invisible in layout from the start to stop it fla…
  app/src/main/res/layout/fragment_sessions_tab.xml
Labels: bug

#592 Include fragment module in test app component
  app/src/androidTest/java/pl/llp/aircasting/TestAppComponent.kt
Labels: chore

#590 Display empty string when the selected stream is null
  app/src/main/java/pl/llp/aircasting/data/model/Session.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/charts/Chart.kt
  app/src/main/res/layout/session_card.xml
Labels: bug

#597 Update | Gradle
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/Versions.kt
Labels: Updates, chore

#602 Missing 'hour range' and '1 min avg' on chart
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/charts/Chart.kt
Labels: bug, Refactoring

#601 AB: "PM2.5" should be the default parameter
  app/src/main/java/pl/llp/aircasting/data/model/Session.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionPresenter.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionViewMvcImpl.kt
Labels: bug, test, Refactoring

#609 Fragment Manager | Fix tests
  app/src/main/java/pl/llp/aircasting/ui/view/screens/search/SearchFixedBottomSheet.kt
Labels: bug, Refactoring

#611 Display chosen thresholds from slider on HLUDialog
  app/src/main/java/pl/llp/aircasting/ui/view/screens/session_view/hlu/HLUDialog.kt
Labels: bug

#614 Set correct checkbox drawable resource
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/DeleteSessionBottomSheet.kt
Labels: chore

#613 Check for all streams loaded only in local airbeam sessions to make m…
  app/src/main/java/pl/llp/aircasting/data/model/Session.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionPresenter.kt
Labels: bug

#612 Make size of labels fixed to prevent recalculation and wobbling of th…
  app/src/main/res/layout/hlu_slider.xml
  app/src/main/res/values/styles.xml
Labels: bug

#615 Follow a session > record mobile sound level session
  app/src/main/java/pl/llp/aircasting/ui/view/fragments/DashboardFragment.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionsController.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/following/FollowingController.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/lets_begin/LetsBeginController.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/main/MainActivity.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/main/MainController.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/main/MainViewMvc.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/main/MainViewMvcImpl.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/new_session/NewSessionActivity.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/new_session/NewSessionController.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/session_view/SessionDetailsViewController.kt
  app/src/main/java/pl/llp/aircasting/ui/view/screens/settings/SettingsController.kt
  app/src/main/java/pl/llp/aircasting/util/extensions/ActivityExtensions.kt
  app/src/main/java/pl/llp/aircasting/util/extensions/ContextExtensions.kt
Labels: bug, test, Refactoring

#616 Navigation | Refactor
  app/src/main/java/pl/llp/aircasting/ui/view/screens/main/MainViewMvcImpl.kt
Labels: bug, Refactoring

#620 CircleCI | Firebase Test Lab
  .circleci/config.yml
Labels: Refactoring, chore

#622 Mobile active: make expanded card the default state
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/active/MobileActiveSessionViewMvcImpl.kt
Labels: bug, Refactoring

#618 Navigation | Refactor 2
  .circleci/config.yml
Labels: bug, wip, Refactoring

#623 New session blank screen location permission
  app/src/main/java/pl/llp/aircasting/ui/view/screens/new_session/NewSessionController.kt
Labels: bug

#625 New release | Update
  app/src/main/res/values-b+es/strings.xml
  app/src/main/res/values-fr-rFR/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: Refactoring

#629 Make building outlines visible on maps
  app/src/main/res/raw/map_style
Labels: chore

#628 Re-adjust menu visibility on (un)follow button click in following screen
  app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/following/FollowingController.kt
Labels: bug

#631 Truncate creationTime of mobile measurement to seconds for backend ex…
  app/src/main/java/pl/llp/aircasting/util/events/NewMeasurementEvent.kt
Labels: bug, enhancement

#632 Let's start | Layout
  app/src/main/res/layout/fragment_lets_begin.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: bug, Refactoring

#635 The gesture for the map on the BottomSheet when moving it down
  app/src/main/res/layout/search_follow_bottom_sheet.xml
Labels: bug, Search Feature

#637 Mobile active > add a note: attach photo - UI
  app/src/main/res/layout/add_note_bottom_sheet.xml
  app/src/main/res/values/styles.xml
Labels: enhancement, Updates

#642 Change lets begin background color to match rendering
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: chore

#643 mobile dormant & fixed: spinner obscured by map button
  app/src/main/res/layout/session_card.xml
Labels: chore

#645 ASAP - Replace wrong id in layout
  app/src/main/res/layout/fragment_lets_begin.xml
Labels: crash
